run: Meerkat.o Person.o cart.o aircraft.o main.o
	g++ Meerkat.o Person.o cart.o aircraft.o main.o  -Wall -o run

Meerkat.o: Meerkat.cpp
	g++ -c Meerkat.cpp

Person.o: Person.cpp
	g++ -c Person.cpp

cart.o: cart.cpp
	g++ -c cart.cpp

aircraft.o: aircraft.cpp
	g++ -c aircraft.cpp

main.o: main.cpp
	g++ -c main.cpp