run: entity.o maze.o pac.o ghost.o red.o blue.o pink.o orange.o main.o
	g++ entity.o maze.o pac.o ghost.o red.o blue.o pink.o orange.o main.o  -Wall -o run

entity.o: entity.cpp
	g++ -c entity.cpp

maze.o: maze.cpp
	g++ -c maze.cpp

pac.o: pac.cpp
	g++ -c pac.cpp

ghost.o: ghost.cpp
	g++ -c ghost.cpp

red.o: red.cpp
	g++ -c red.cpp

blue.o: blue.cpp
	g++ -c blue.cpp

pink.o: pink.cpp
	g++ -c pink.cpp

orange.o: orange.cpp
	g++ -c orange.cpp

main.o: main.cpp
	g++ -c main.cpp