run: entity.o maze.o pac.o ghost.o main.o
	g++ entity.o maze.o pac.o ghost.o main.o  -Wall -o run

entity.o: entity.cpp
	g++ -c entity.cpp

maze.o: maze.cpp
	g++ -c maze.cpp

pac.o: pac.cpp
	g++ -c pac.cpp

ghost.o: ghost.cpp
	g++ -c ghost.cpp

main.o: main.cpp
	g++ -c main.cpp