run: MapGeneric.o MapTriple.o MapSquare.o MapAbsoluteValue.o main.o
	g++ MapGeneric.o MapTriple.o MapSquare.o MapAbsoluteValue.o main.o -Wall -o run

MapGeneric.o: MapGeneric.cpp
	g++ -c MapGeneric.cpp

MapTriple.o: MapTriple.cpp
	g++ -c MapTriple.cpp

MapSquare.o: MapSquare.cpp
	g++ -c MapSquare.cpp

MapAbsoluteValue.o: MapAbsoluteValue.cpp
	g++ -c MapAbsoluteValue.cpp

main.o: main.cpp
	g++ -c main.cpp
