run: MapGeneric.o MapTriple.o MapSquare.o MapAbsoluteValue.o FilterGeneric.o FilterOdd.o FilterNonPositive.o FilterForTwoDigitPositive.o ReduceGeneric.o ReduceMinimum.o ReduceGCD.o main.o
	g++ MapGeneric.o MapTriple.o MapSquare.o MapAbsoluteValue.o FilterGeneric.o FilterOdd.o FilterNonPositive.o FilterForTwoDigitPositive.o ReduceGeneric.o ReduceMinimum.o ReduceGCD.o main.o -Wall -o run

MapGeneric.o: MapGeneric.cpp
	g++ -c MapGeneric.cpp

MapTriple.o: MapTriple.cpp
	g++ -c MapTriple.cpp

MapSquare.o: MapSquare.cpp
	g++ -c MapSquare.cpp

MapAbsoluteValue.o: MapAbsoluteValue.cpp
	g++ -c MapAbsoluteValue.cpp

FilterGeneric.o: FilterGeneric.cpp
	g++ -c FilterGeneric.cpp

FilterOdd.o: FilterOdd.cpp
	g++ -c FilterOdd.cpp

FilterNonPositive.o: FilterNonPositive.cpp
	g++ -c FilterNonPositive.cpp

FilterForTwoDigitPositive.o: FilterForTwoDigitPositive.cpp
	g++ -c FilterForTwoDigitPositive.cpp

ReduceGeneric.o: ReduceGeneric.cpp
	g++ -c ReduceGeneric.cpp

ReduceMinimum.o: ReduceMinimum.cpp
	g++ -c ReduceMinimum.cpp

ReduceGCD.o: ReduceGCD.cpp
	g++ -c ReduceGCD.cpp

main.o: main.cpp
	g++ -c main.cpp
