#!/bin/bash
# takes two switch inputs (any order)
# reads input from stdin until end of file (eof)
# caesar encode each line and write to output
# do this by calling the create_pattern.sh file

#!/bin/bash
# Given an input parameter, cyclicly perform caesar encoding on a given phrase.
# Check for the input switches:

# Loop for as many input arguments are given
while [[ $1 -gt 0 ]] ;
	current=$1
	shift;
	do
		# Read the input argument
		if [[ $current = "-n" ]]
		then
			parameter=$1
		fi

		if [[ $current = "-u" ]] ;
		then
			upper=true ;
		fi
done

# The cyclic pattern repeats after 26 so calculate the remainder of the input divided by 26
n=$(expr $parameter % 26)

# Encode the given phrase:
# Upper Case:
if [[ $upper = "true" ]]
then
	start="[A-XY-Z]"
	translation="'[A-Z]' '[B-ZA]'"
else
	# Lower Case:
	start="[a-xy-z]"
	translation="'[a-z]' '[b-za]'"
fi