#!/bin/bash
# reads input from stdin until end of file (eof)
# caesar encode each line and write to output
# do this by calling the create_pattern.sh file

# Call the create_pattern function storing the result
translation_pattern=$(./create_pattern $*)

# Find the starting span from the output of create_pattern
# Either A-Z or a-z
starting_span=${translation_pattern[@]:4:1}-${translation_pattern[@]:3:1}
# Add square brackets enclosing the starting span
starting_span="[$starting_span]"

# Read input until eof
phrase=$( cat )

# Translate the input
phrase=$( echo "$phrase" | tr $starting_span $translation_pattern )

# Write to output
echo "$phrase"