#!/bin/bash
# takes two switch inputs (any order)
# reads input from stdin until end of file (eof)
# caesar encode each line and write to output
# do this by calling the create_pattern.sh file

./create_pattern $*

read phrase
echo $phrase

