#!/bin/bash
# given an input parameter, cyclicly perform caesar encoding on a given phrase.

# Get the phrase to be encoded from the user
read -p "Enter the phrase to be encoded: " phrase

# The cyclic pattern repeats after 26 so calculate the remainder of the input divided by 26
n=$(expr $1 % 26)

# Loop n times
for ((i=0; i<n; i++))
	do
		# Cycle each character once
		phrase=$( echo "$phrase" | tr '[A-Z]' '[B-ZA]' )
done

# Write the encoded phrase to output
echo "$phrase"