#!/bin/bash
# Check for the input switches:

# Loop for as many input arguments are given
while [[ $1 -gt 0 ]] ;
	current=$1
	shift;
	do
		# Read the input argument
		if [[ $current = "-n" ]]
		then
			parameter=$1
		fi

		if [[ $current = "-u" ]] ;
		then
			upper=true ;
		fi
done

echo "$upper"
echo "$parameter"