#!/bin/bash

# Store the content of the parameter file into a variable
phrase=$(<$1)

for ((i=1; i<26; i++))
	do
		echo "Shift $i"
		# Cycle each character once
		phrase=$( echo "$phrase" | tr '[A-Z]' '[B-ZA]' )
		echo $phrase
done